services:

  backend:
    build: ./backend
    container_name: mahsoul_backend

    command:
      - "hypercorn"
      - "src.main:app"
      - "--bind"
      - "0.0.0.0:8000"
      - "--access-logfile"
      - "-"
      - "--reload"
    ports:
      - "8000:8000"

    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      DOMAIN_NAME: ${DOMAIN_NAME}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      POSTGRES_HOST: db        
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}

    volumes:
      - ./backend/src:/app/src  

    depends_on:
      - db

    networks:
      - public_net
      - private_net   

    restart: unless-stopped


  db:
    image: postgres:16-alpine
    container_name: mahsoul_db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - software_app:/var/lib/postgresql/data

    networks:
      - private_net   

    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    container_name: mahsoul_frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

    networks:
      - public_net        
      - private_net

    restart: unless-stopped
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000


  reverse_proxy:
    image: nginx:alpine
    container_name: mahsoul_reverse_proxy

    ports:
      - "80:80"        

    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - backend
      - frontend

    networks:
      - public_net
      - private_net

    restart: unless-stopped


networks:
  public_net:
    driver: bridge

  private_net:
    driver: bridge
    internal: false   


volumes:
  software_app:
